### ISSUE TITLE
Error thrown on this line when using Update-AzTableRow

### ISSUE THREAD

**Issue by webash** [paulomarquesc/AzureRmStorageTable#58] opened 2020-08-26 00:45 UTC
https://github.com/paulomarquesc/AzureRmStorageTable/blob/f1ebed2589bf7fd6def21d4eb3e62c839027d21f/AzureRmStorageTableCoreHelper.psm1#L663

Getting an error when using Update-AzTableRow on line 663 in the main module. See below:
![image](https://user-images.githubusercontent.com/6205899/91241895-e0471e80-e73d-11ea-987a-2ab6c0964805.png)

**Comment by webash** [comment] 2020-08-26 12:10
Somehow it still appears to be updating the record... not sure I understand what's going on here...

**Comment by webash** [comment] 2020-09-15 16:11
@paulomarquesc any chance these commands could be moved into an official MS module to keep them current? :)

**Comment by paulomarquesc** [comment] 2020-09-16 21:03
Hi webash, can you please provide the code snippet to the point where you execute the update? To your question, moving to Az is not planned yet, @PaulCheng and @sakash279 can add more on this.

**Comment by PaulCheng** [comment] 2020-09-18 00:38
Regarding to moving these functions to the official azure ps module, it is what we have in the backlog, but we are just not there yet.  There is no eta I can provide either at this point.

**Comment by webash** [comment] 2020-09-22 18:22
It is embedded in a much larger script, for but illustration purposes I've simplified down to this pseudo-code:

```PowerShell
$TableResults = Get-AzTableRow -Table $StorageTable.CloudTable;

$TableResults | ForEach-Object {
    $row = $_;
    $PendingTableRow = $row | Add-Member -PassThru -NotePropertyMembers @{
        NewOne = "AAA";
        NewTwo = "BBB";
        NewThree = "CCC";
    };
    $PendingTableRow.ExistingProperty = "Changing this property"

    Update-AzTableRow -Table $StorageTable.CloudTable -Entity $PendingTableRow | Out-Null;
}
```

**Comment by paulomarquesc** [comment] 2021-02-20 01:39
Hi Webash, getting back to this thread, I could not reproduce your issue. I've got a different error due to how you you're doing $row = $_. 

I modified it a little bit since the $row = $_ is not necessary and it runs without issues:

```powershell
$TableResults | ForEach-Object {
    $PendingTableRow = $_ | Add-Member -PassThru -NotePropertyMembers @{
        NewOne = "AAA";
        NewTwo = "BBB";
        NewThree = "CCC";
    };
    $PendingTableRow.status = "Changing this property"

    Update-AzTableRow -Table $table -Entity $PendingTableRow
}
```

This is my clean execution:

![image](https://user-images.githubusercontent.com/17993275/108578915-c1d37180-72e1-11eb-901c-ea2933245f2b.png)

**Closed as completed by paulomarquesc** 2021-02-20 01:39 UTC
